-- liquibase formatted sql

-- changeset AstrashenyaDmitriy:1
CREATE TABLE IF NOT EXISTS image
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_path  TEXT,
    file_size  BIGINT,
    media_type TEXT
);

CREATE TABLE IF NOT EXISTS users
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email            TEXT NOT NULL,
    password         TEXT NOT NULL,
    confirm_password TEXT NOT NULL,
    first_name       TEXT NOT NULL,
    last_name        TEXT NOT NULL,
    specialization   TEXT NOT NULL,
    city             TEXT NOT NULL,
    birth_date       DATE NOT NULL,
    about_me         TEXT NOT NULL,
    image            INTEGER  REFERENCES image (id),
    role             TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS education
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    university_name TEXT    NOT NULL,
    speciality      TEXT    NOT NULL,
    years_of_study  TEXT    NOT NULL,
    user_id         INTEGER NOT NULL REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS socials
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link           TEXT    NOT NULL,
    user_id        INTEGER NOT NULL REFERENCES users (id)
);
